########################################
## 按《软件日志记录规范》输出日志配置 ##
########################################
########################################
##        以下为运行日志的配置        ##
##        运行日志按级别输出          ##
########################################
## 级别fatal（致命错误）的日志输出配置 
log4j.appender.default_fatal=org.apache.log4j.RollingFileAppender
log4j.appender.default_fatal.File=../../../logs/media/dac.media.fatal.log
log4j.appender.default_fatal.MaxFileSize=25MB
log4j.appender.default_fatal.MaxBackupIndex=10
log4j.appender.default_fatal.Append=true
log4j.appender.default_fatal.Threshold=FATAL
log4j.appender.default_fatal.layout=org.apache.log4j.PatternLayout
log4j.appender.default_fatal.layout.ConversionPattern= %d{yyyy-MM-ddTHH:mm:ss.SSSZ} %-p %.16c [%t] %m%n
## 级别error（错误）的日志输出配置 
log4j.appender.default_error=org.apache.log4j.RollingFileAppender
log4j.appender.default_error.File=../../../logs/media/dac.media.error.log
log4j.appender.default_error.MaxFileSize=25MB
log4j.appender.default_error.MaxBackupIndex=10
log4j.appender.default_error.Append=true
log4j.appender.default_error.Threshold=ERROR
log4j.appender.default_error.layout=org.apache.log4j.PatternLayout
log4j.appender.default_error.layout.ConversionPattern= %d{yyyy-MM-ddTHH:mm:ss.SSSZ} %-p %.16c [%t] %m%n
## 级别warn（警告）的日志输出配置 
log4j.appender.default_warn=org.apache.log4j.RollingFileAppender
log4j.appender.default_warn.File=../../../logs/media/dac.media.warn.log
log4j.appender.default_warn.MaxFileSize=25MB
log4j.appender.default_warn.MaxBackupIndex=10
log4j.appender.default_warn.Append=true
log4j.appender.default_warn.Threshold=WARN
log4j.appender.default_warn.layout=org.apache.log4j.PatternLayout
log4j.appender.default_warn.layout.ConversionPattern= %d{yyyy-MM-ddTHH:mm:ss.SSSZ} %-p %.16c [%t] %m%n
## 级别info（信息）的日志输出配置 
log4j.appender.default_info=org.apache.log4j.RollingFileAppender
log4j.appender.default_info.File=../../../logs/media/dac.media.info.log
log4j.appender.default_info.MaxFileSize=25MB
log4j.appender.default_info.MaxBackupIndex=10
log4j.appender.default_info.Append=true
log4j.appender.default_info.Threshold=INFO
log4j.appender.default_info.layout=org.apache.log4j.PatternLayout
log4j.appender.default_info.layout.ConversionPattern= %d{yyyy-MM-ddTHH:mm:ss.SSSZ} %-p %.16c [%t] %m%n
## 级别debug（调试）的日志输出配置 
log4j.appender.default_debug=org.apache.log4j.RollingFileAppender
log4j.appender.default_debug.File=../../../logs/media/dac.media.debug.log
log4j.appender.default_debug.MaxFileSize=25MB
log4j.appender.default_debug.MaxBackupIndex=10
log4j.appender.default_debug.Append=true
log4j.appender.default_debug.Threshold=DEBUG
log4j.appender.default_debug.layout=org.apache.log4j.PatternLayout
log4j.appender.default_debug.layout.ConversionPattern= %d{yyyy-MM-ddTHH:mm:ss.SSSZ} %-p %.16c [%t] %m%n
## 级别trace（调试跟踪）的日志输出配置 
log4j.appender.default_trace=org.apache.log4j.RollingFileAppender
log4j.appender.default_trace.File=../../../logs/media/dac.media.trace.log
log4j.appender.default_trace.MaxFileSize=25MB
log4j.appender.default_trace.MaxBackupIndex=10
log4j.appender.default_trace.Append=true
log4j.appender.default_trace.Threshold=TRACE
log4j.appender.default_trace.layout=org.apache.log4j.PatternLayout
log4j.appender.default_trace.layout.ConversionPattern= %d{yyyy-MM-ddTHH:mm:ss.SSSZ} %-p %.16c [%t] %m%n

#Console  
log4j.appender.Console=org.apache.log4j.ConsoleAppender  
log4j.appender.Console.layout=org.apache.log4j.PatternLayout  
log4j.appender.Console.Threshold=ERROR
log4j.appender.Console.layout.ConversionPattern=%d{yyyy-MM-ddTHH:mm:ss.SSSZ}   %-p %.16c [%t] %m%n

######################################## 
##        以下为其他日志的配置        ##
########################################
#设置 DRVNET
log4j.logger.DRVNET=DEBUG, DRVNET
log4j.appender.DRVNET=org.apache.log4j.RollingFileAppender
log4j.appender.DRVNET.File=../../../logs/media/depend/drvnet.log
log4j.appender.DRVNET.MaxFileSize=25MB
log4j.appender.DRVNET.MaxBackupIndex=10
log4j.appender.DRVNET.Append=true
log4j.appender.DRVNET.Threshold=DEBUG
log4j.appender.DRVNET.layout=org.apache.log4j.PatternLayout
log4j.appender.DRVNET.layout.ConversionPattern=%d{yyyy-MM-ddTHH:mm:ss.SSSZ}   %-p %.16c [%t] %m%n
log4j.additivity.DRVNET=false

#设置HikUtility
#log4j.logger.HikUtility=DEBUG, HikUtility
log4j.appender.HikUtility=org.apache.log4j.RollingFileAppender
log4j.appender.HikUtility.File=../../../logs/media//HikUtility.log
log4j.appender.HikUtility.MaxFileSize=50MB
log4j.appender.HikUtility.MaxBackupIndex=12
log4j.appender.HikUtility.Append=true
log4j.appender.HikUtility.Threshold=DEBUG
log4j.appender.HikUtility.layout=org.apache.log4j.PatternLayout
log4j.appender.HikUtility.layout.ConversionPattern=%d [%t] %-5p %.16c - %m%n
#log4j.additivity.HikUtility = false

#设置NodeProxy
log4j.appender.NODEPROXY_appender=org.apache.log4j.RollingFileAppender
log4j.appender.NODEPROXY_appender.File=../../../logs/media/depend/dac.media.NodeProxy.debug.log
log4j.appender.NODEPROXY_appender.MaxFileSize=25MB
log4j.appender.NODEPROXY_appender.MaxBackupIndex=10
log4j.appender.NODEPROXY_appender.Append=true
log4j.appender.NODEPROXY_appender.Threshold=DEBUG
log4j.appender.NODEPROXY_appender.layout=org.apache.log4j.PatternLayout
log4j.appender.NODEPROXY_appender.layout.ConversionPattern= %d{yyyy-MM-ddTHH:mm:ss.SSSZ} %-p %.16c [%t] %m%n

#设置取流插件日志
log4j.appender.PAG_appender=org.apache.log4j.RollingFileAppender
log4j.appender.PAG_appender.File=../../../logs/media/depend/dac.media.plugins.debug.log
log4j.appender.PAG_appender.MaxFileSize=25MB
log4j.appender.PAG_appender.MaxBackupIndex=10
log4j.appender.PAG_appender.Append=true
log4j.appender.PAG_appender.Threshold=WARN
log4j.appender.PAG_appender.layout=org.apache.log4j.PatternLayout
log4j.appender.PAG_appender.layout.ConversionPattern= %d{yyyy-MM-ddTHH:mm:ss.SSSZ} %-p %.16c [%t] %m%n

#设置Crash
log4j.appender.Crash=org.apache.log4j.RollingFileAppender
log4j.appender.Crash.File=../../../logs/media/depend/dac.media.Crash.log
log4j.appender.Crash.MaxFileSize=25MB
log4j.appender.Crash.MaxBackupIndex=10
log4j.appender.Crash.Append=true
log4j.appender.Crash.Threshold=INFO
log4j.appender.Crash.layout=org.apache.log4j.PatternLayout
log4j.appender.Crash.layout.ConversionPattern= %d{yyyy-MM-ddTHH:mm:ss.SSSZ} %-p %.16c [%t] %m%n
 
######################################## 
##        以下为追踪日志的配置        ##
########################################

log4j.appender.default_dst=org.apache.log4j.RollingFileAppender
log4j.appender.default_dst.File=../../../logs/media/depend/dac.media.dts.log
log4j.appender.default_dst.MaxFileSize=25MB
log4j.appender.default_dst.MaxBackupIndex=10
log4j.appender.default_dst.Append=true
log4j.appender.default_dst.Threshold=TRACE
log4j.appender.default_dst.layout=org.apache.log4j.PatternLayout
log4j.appender.default_dst.layout.ConversionPattern= %d [%t] %m%n

########################################

##       以下为日志输出规则配置       ##

########################################
log4j.rootLogger=WARN,default_debug
#log4j.rootLogger=DEBUG,default_info,default_debug,default_error,default_trace,default_warn,default_fatal

########################################

##    以下为运行日志输出规则配置      ##

########################################
#log4j.logger.LogTest=TRACE,default_info,default_debug,default_error,default_trace,default_warn,default_fatal
#log4j.logger.TrackLog=FATAL,default_dst
#log4j.additivity.TrackLog = false

log4j.logger.TrackLog=OFF

#设置Crash日志打印级别
#log4j.logger.Crash=INFO, Crash
#log4j.additivity.Crash = false

log4j.logger.PAG=DEBUG,PAG_appender
log4j.additivity.PAG=false

#log4j.logger.NODEPROXY=DEBUG,NODEPROXY_appender
#log4j.additivity.NODEPROXY=false

##hlog.async=false
#hlog.secret.show=true
#hlog.secret.encrypt=true