@bic.serviceDirectory.ip=10.33.43.48
@bic.serviceDirectory.port=8001
@bic.serviceDirectory.protocol=http
@bic.serviceDirectory.context=/bic
@bic.cas.ip=10.33.43.48
@bic.cas.port=8001
@bic.cas.protocol=http
@bic.cas.context=/bic
@bic.centerCas.ip=10.33.43.48
@bic.centerCas.port=8001
@bic.centerCas.protocol=http
@bic.centerCas.context=/center_cas
@bic.bic.ip=10.33.43.48
@bic.bic.port=8001
@bic.bic.protocol=http
@bic.bic.context=/bic
@bic.license.ip=10.33.43.48
@bic.license.port=8001
@bic.license.protocol=http
@bic.license.context=/bic
@bic.log.ip=10.33.43.48
@bic.log.port=8001
@bic.log.protocol=http
@bic.log.context=/center_log
@bic.notify.ip=10.33.43.48
@bic.notify.port=7002
@bic.notify.username=admin
@bic.notify.password=EQAQAA3hiEE50omeiU/FlbOgxp1MhA1iCOJ/+z/C5RP0XfkMgS5PfFRDyFE4l/j8H+P6bA==
@agent.agentNo=053B2204-5A6F-4126-A0DF-A9D022D98A90
das.@instanceList=das.4
dacldap.@instanceList=dacldap.4
dmc.@instanceList=dmc.4
dms.@instanceList=dms.4
dmsdb.@instanceList=dmsdb.4
dmsqueue.@instanceList=dmsqueue.4
das.4.streamPortRangeUdp=15000-16999
das.4.rtspPort=655
das.4.webPort=7302
das.4.@logLevel=TRACE
das.4.@ip=10.33.43.48,169.254.93.102
das.4.@indexCode=9695b936-f399-470c-ac15-4668a6df9856
das.4.webSocketPort=7314
das.4.clusterPort=7307
das.4.streamPortRangeTcp=15000-16999
dacldap.4.@parent.@componentId=@bic
dacldap.4.@parent.@rootDn=dc=platform,dc=hikvision,dc=com
dacldap.4.@parent.protocol=ldap
dacldap.4.@parent.@username=ou=dac,ou=componentaccounts,dc=platform,dc=hikvision,dc=com
dacldap.4.@parent.@password=EQAQAIHDXQHyC8waPu7xGQqiU2QCiywnuDqSQwSjZQTF/cH19+1ewye8cPYzWRB5B81RMA==
dacldap.4.@indexCode=
dacldap.4.@parent.@componentVersion=
dacldap.4.@parent.@ip=10.33.43.48
dacldap.4.@parent.port=7003
dmc.4.@logLevel=TRACE
dmc.4.@indexCode=0f034c69-e767-4e8e-8d3d-6cfc1ead05c2
dmc.4.webPort=8029
dmc.4.rtspPort=550
dmc.4.@ip=10.33.43.48,169.254.93.102
dms.4.@parent.@componentVersion=1.0.0
dms.4.@parent.@context=/dac
dms.4.@logLevel=TRACE
dms.4.@indexCode=8c40ad47-1cbe-48ca-b69c-50a4fc34ab85
dms.4.@parent.@componentId=tomcat85win64
dms.4.@parent.@ip=10.33.43.48
dms.4.@parent.webPort=8080
dmsdb.4.@parent.@componentVersion=1.0.0
dmsdb.4.@indexCode=
dmsdb.4.@parent.@dbusername=dac_dmsdb_user
dmsdb.4.@parent.@componentId=postgresql96win64
dmsdb.4.@parent.@dbpassword=EQAQAH4kPTSKrve2qX6aV1kOerCWDmhGfYxVClJMKxxfn81M8XMln3xNO+EOhwqUPospRA==
dmsdb.4.@parent.@dbname=dac_dmsdb
dmsdb.4.@parent.@ip=10.33.43.48
dmsdb.4.@parent.port=7017
dmsqueue.4.@parent.@componentVersion=1.0.0
dmsqueue.4.@parent.@username=admin
dmsqueue.4.@indexCode=ce258876-1e7a-41fa-983e-319771f9d66a
dmsqueue.4.@parent.@componentId=activemq514win64
dmsqueue.4.@parent.@password=EQAQAFQ+1SpAvPk7uPnuSDcutSYU83hjOLFaNgunLG/Jz2h1b3Co+rp060EphCWA7w3jlw==
dmsqueue.4.@parent.@queuePrefix=dac.dmsqueue
dmsqueue.4.@parent.@ip=10.33.43.48
dmsqueue.4.@parent.memoryLimit=16
dmsqueue.4.@parent.memoryUsage=128
dmsqueue.4.@parent.port=7018
dmsqueue.4.@parent.storeUsage=512
dmsqueue.4.@parent.tempUsage=1024
dmsqueue.4.@parent.Xms=128
dmsqueue.4.@parent.Xmx=256
