@componentPath=D:/Hikvision/components/dac.4
dmsdb.@index=4
dmsdb.@serviceName=hik.dac.dmsdb.4
dmsdb.@notify.@clientid=dac.dmsdb.053B2204-5A6F-4126-A0DF-A9D022D98A90.4
das.@index=4
das.@serviceName=hik.dac.das.4
das.@notify.@clientid=dac.das.053B2204-5A6F-4126-A0DF-A9D022D98A90.4
dacldap.@index=4
dacldap.@serviceName=hik.dac.dacldap.4
dacldap.@notify.@clientid=dac.dacldap.053B2204-5A6F-4126-A0DF-A9D022D98A90.4
dms.@index=4
dms.@context=/dac
dms.@notify.@clientid=dac.dms.053B2204-5A6F-4126-A0DF-A9D022D98A90.4
dmc.@index=4
dmc.@serviceName=hik.dac.dmc.4
dmc.@notify.@clientid=dac.dmc.053B2204-5A6F-4126-A0DF-A9D022D98A90.4
dmsqueue.@index=4
dmsqueue.@serviceName=hik.dac.dmsqueue.4
dmsqueue.@notify.@clientid=dac.dmsqueue.053B2204-5A6F-4126-A0DF-A9D022D98A90.4
