
user  root;
worker_processes  1;
error_log  logs/error.log;
pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  300;

    upstream gateway_server {
        server 127.0.0.1:8081;
    }

    server {
        listen       80;
        server_name  localhost;

        location / {
            root   html;
            index  index.html;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }

        location /ISAPI {
            proxy_pass http://gateway_server/ISAPI;
            proxy_http_version 1.1;
            proxy_set_header Host $host:$server_port;
        }

        location /SDK {
            proxy_pass http://gateway_server/SDK;
            proxy_http_version 1.1;
        }
    }
}
