########################################

##        以下为运行日志的配置        ##

##        运行日志按级别输出          ##

########################################

##   级别fatal（致命错误）的日志输出配置
log4j.appender.default_fatal=org.apache.log4j.RollingFileAppender
log4j.appender.default_fatal.File=./logs/pss_0.1.fatal.log
log4j.appender.default_fatal.MaxFileSize=25MB
log4j.appender.default_fatal.MaxBackupIndex=10
log4j.appender.default_fatal.Append=true
log4j.appender.default_fatal.Threshold=FATAL
log4j.appender.default_fatal.layout=org.apache.log4j.PatternLayout
log4j.appender.default_fatal.layout.ConversionPattern=%d{yyyy-MM-ddTHH:mm:ss.SSSZ}   %-p %.16c [%t] %m%n

##   级别error（错误）的日志输出配置
log4j.appender.default_error=org.apache.log4j.RollingFileAppender
log4j.appender.default_error.File=./logs/pss_0.1.error.log
log4j.appender.default_error.MaxFileSize=25MB
log4j.appender.default_error.MaxBackupIndex=10
log4j.appender.default_error.Append=true
log4j.appender.default_error.Threshold=ERROR
log4j.appender.default_error.layout=org.apache.log4j.PatternLayout
log4j.appender.default_error.layout.ConversionPattern=%d{yyyy-MM-ddTHH:mm:ss.SSSZ}   %-p %.16c [%t] %m%n

##   级别warn（警告）的日志输出配置
log4j.appender.default_warn=org.apache.log4j.RollingFileAppender
log4j.appender.default_warn.File=./logs/pss_0.1.warn.log
log4j.appender.default_warn.MaxFileSize=25MB
log4j.appender.default_warn.MaxBackupIndex=10
log4j.appender.default_warn.Append=true
log4j.appender.default_warn.Threshold=WARN
log4j.appender.default_warn.layout=org.apache.log4j.PatternLayout
log4j.appender.default_warn.layout.ConversionPattern=%d{yyyy-MM-ddTHH:mm:ss.SSSZ}   %-p %.16c [%t] %m%n

##   级别info（信息）的日志输出配置
log4j.appender.default_info=org.apache.log4j.RollingFileAppender
log4j.appender.default_info.File=../../logs/pss/pss_0.1.info.log
log4j.appender.default_info.MaxFileSize=25MB
log4j.appender.default_info.MaxBackupIndex=10
log4j.appender.default_info.Append=true
log4j.appender.default_info.Threshold=INFO
log4j.appender.default_info.layout=org.apache.log4j.PatternLayout
log4j.appender.default_info.layout.ConversionPattern=%d{yyyy-MM-ddTHH:mm:ss.SSSZ}   %-p %.16c [%t] %m%n

##   级别debug（调试）的日志输出配置
log4j.appender.default_debug=org.apache.log4j.RollingFileAppender
log4j.appender.default_debug.File=../../logs/pss/pss_0.1.debug.log
log4j.appender.default_debug.MaxFileSize=25MB
log4j.appender.default_debug.MaxBackupIndex=10
log4j.appender.default_debug.Append=true
log4j.appender.default_debug.Threshold=DEBUG
log4j.appender.default_debug.layout=org.apache.log4j.PatternLayout
log4j.appender.default_debug.layout.ConversionPattern=%d{yyyy-MM-ddTHH:mm:ss.SSSZ}   %-p %.16c [%t] %m%n

##   级别trace（调试跟踪）的日志输出配置
log4j.appender.default_trace=org.apache.log4j.RollingFileAppender
log4j.appender.default_trace.File=../../logs/pss/pss_0.1.trace.log
log4j.appender.default_trace.MaxFileSize=25MB
log4j.appender.default_trace.MaxBackupIndex=10
log4j.appender.default_trace.Append=true
log4j.appender.default_trace.Threshold=TRACE
log4j.appender.default_trace.layout=org.apache.log4j.PatternLayout
log4j.appender.default_trace.layout.ConversionPattern=%d{yyyy-MM-ddTHH:mm:ss.SSSZ}   %-p %.16c [%t] %m%n

#Console  
log4j.appender.Console=org.apache.log4j.ConsoleAppender  
log4j.appender.Console.layout=org.apache.log4j.PatternLayout  
log4j.appender.Console.Threshold=ERROR
log4j.appender.Console.layout.ConversionPattern=%d{yyyy-MM-ddTHH:mm:ss.SSSZ}   %-p %.16c [%t] %m%n

######################################## 
##        以下为其他日志的配置        ##
########################################
#设置 DRVNET
log4j.logger.DRVNET=DEBUG, DRVNET
log4j.appender.DRVNET=org.apache.log4j.RollingFileAppender
log4j.appender.DRVNET.File=../../logs/pss/depend/drvnet.log
log4j.appender.DRVNET.MaxFileSize=25MB
log4j.appender.DRVNET.MaxBackupIndex=10
log4j.appender.DRVNET.Append=true
log4j.appender.DRVNET.Threshold=DEBUG
log4j.appender.DRVNET.layout=org.apache.log4j.PatternLayout
log4j.appender.DRVNET.layout.ConversionPattern=%d{yyyy-MM-ddTHH:mm:ss.SSSZ}   %-p %.16c [%t] %m%n
log4j.additivity.DRVNET=false

#设置HikUtility
#log4j.logger.HikUtility=DEBUG, HikUtility
log4j.appender.HikUtility=org.apache.log4j.RollingFileAppender
log4j.appender.HikUtility.File=../../logs/pss/app/HikUtility.log
log4j.appender.HikUtility.MaxFileSize=50MB
log4j.appender.HikUtility.MaxBackupIndex=12
log4j.appender.HikUtility.Append=true
log4j.appender.HikUtility.Threshold=DEBUG
log4j.appender.HikUtility.layout=org.apache.log4j.PatternLayout
log4j.appender.HikUtility.layout.ConversionPattern=%d [%t] %-5p %.16c - %m%n
#log4j.additivity.HikUtility = false

#设置hplug
#log4j.logger.hplug=DEBUG, hplug
#log4j.appender.hplug=org.apache.log4j.RollingFileAppender
#log4j.appender.hplug.File=./log/Hplug.log
#log4j.appender.hplug.MaxFileSize=50MB
#log4j.appender.hplug.MaxBackupIndex=12
#log4j.appender.hplug.Append=true
#log4j.appender.hplug.Threshold=DEBUG
#log4j.appender.hplug.layout=org.apache.log4j.PatternLayout
#log4j.appender.hplug.layout.ConversionPattern=%d [%t] %-5p %.16c - %M - %l - %m%n
#log4j.additivity.hplug = false

#设置CRASH
#log4j.logger.Crash=TRACE, Crash
log4j.appender.Crash=org.apache.log4j.RollingFileAppender
log4j.appender.Crash.File=.../../logs/pss/app/third_debug.log
log4j.appender.Crash.MaxFileSize=50MB
log4j.appender.Crash.MaxBackupIndex=12
log4j.appender.Crash.Append=true
log4j.appender.Crash.Threshold=TRACE
log4j.appender.Crash.layout=org.apache.log4j.PatternLayout
log4j.appender.Crash.layout.ConversionPattern=%d [%t] %-5p %.16c - %M - %l - %m%n
#log4j.additivity.Crash = false

########################################

##       以下为日志输出规则配置       ##

########################################
log4j.rootLogger=WARN,default_debug
#log4j.rootLogger=ERROR,default_info,default_debug,default_error,default_trace,default_warn,default_fatal,Crash,HikUtility
########################################

##    以下为运行日志输出规则配置      ##

########################################
#log4j.logger.LogTest=TRACE,default_info,default_debug,default_error,default_trace,default_warn,default_fatal
#log4j.logger.TrackLog=FATAL,default_dst
log4j.logger.TrackLog=OFF
#log4j.additivity.TrackLog=false

##hlog.async=false
##hlog.secret.show=true
##hlog.secret.encrypt=true