"""Enrollments Period Breaks Association

Revision ID: 0f4aee6ab87c
Revises: 81a3c831ab12
Create Date: 2026-02-21 18:05:54.544684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4aee6ab87c'
down_revision: Union[str, None] = '81a3c831ab12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollments_period_break_id'), table_name='enrollments')
    op.drop_constraint(op.f('enrollments_period_break_id_fkey'), 'enrollments', type_='foreignkey')
    op.drop_column('enrollments', 'period_break_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('period_break_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('enrollments_period_break_id_fkey'), 'enrollments', 'period_breaks', ['period_break_id'], ['id'])
    op.create_index(op.f('ix_enrollments_period_break_id'), 'enrollments', ['period_break_id'], unique=False)
    # ### end Alembic commands ###
