"""Update enrollments for AcademicPeriod relationships

Revision ID: 81a3c831ab12
Revises: 270a446d3abd
Create Date: 2026-02-21 17:26:31.983179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a3c831ab12'
down_revision: Union[str, None] = '270a446d3abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('academic_period_id', sa.UUID(), nullable=False))
    op.add_column('enrollments', sa.Column('period_break_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_enrollments_academic_period_id'), 'enrollments', ['academic_period_id'], unique=False)
    op.create_index(op.f('ix_enrollments_period_break_id'), 'enrollments', ['period_break_id'], unique=False)
    op.create_foreign_key(None, 'enrollments', 'academic_periods', ['academic_period_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'period_breaks', ['period_break_id'], ['id'])
    op.drop_column('enrollments', 'semester')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_index(op.f('ix_enrollments_period_break_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_academic_period_id'), table_name='enrollments')
    op.drop_column('enrollments', 'period_break_id')
    op.drop_column('enrollments', 'academic_period_id')
    # ### end Alembic commands ###
