"""Move ClassSchedules to ClassGroup

Revision ID: 4b18cf510eac
Revises: 69bc40cce567
Create Date: 2026-02-25 02:17:14.385064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b18cf510eac'
down_revision: Union[str, None] = '69bc40cce567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_schedules', sa.Column('class_group_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_class_schedules_academic_period_id'), table_name='class_schedules')
    op.create_index(op.f('ix_class_schedules_class_group_id'), 'class_schedules', ['class_group_id'], unique=False)
    op.drop_constraint(op.f('class_schedules_academic_period_id_fkey'), 'class_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'class_schedules', 'class_groups', ['class_group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('class_schedules', 'academic_period_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_schedules', sa.Column('academic_period_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'class_schedules', type_='foreignkey')
    op.create_foreign_key(op.f('class_schedules_academic_period_id_fkey'), 'class_schedules', 'academic_periods', ['academic_period_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_class_schedules_class_group_id'), table_name='class_schedules')
    op.create_index(op.f('ix_class_schedules_academic_period_id'), 'class_schedules', ['academic_period_id'], unique=False)
    op.drop_column('class_schedules', 'class_group_id')
    # ### end Alembic commands ###
