"""Refactor class group students to use enrollments

Revision ID: 1e58bec1aa42
Revises: 57584c42507f
Create Date: 2026-02-21 21:26:57.412885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e58bec1aa42'
down_revision: Union[str, None] = '57584c42507f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE class_group_students CASCADE")
    op.execute("TRUNCATE TABLE class_group_student_subjects CASCADE")
    op.add_column('class_group_student_subjects', sa.Column('enrollment_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_class_group_student_subjects_student_id'), table_name='class_group_student_subjects')
    op.drop_constraint('uq_cg_student_subject', 'class_group_student_subjects', type_='unique')
    op.create_index(op.f('ix_class_group_student_subjects_enrollment_id'), 'class_group_student_subjects', ['enrollment_id'], unique=False)
    op.create_unique_constraint('uq_cg_enrollment_subject', 'class_group_student_subjects', ['class_group_id', 'enrollment_id', 'subject_id'])
    op.drop_constraint('class_group_student_subjects_student_id_fkey', 'class_group_student_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'class_group_student_subjects', 'enrollments', ['enrollment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('class_group_student_subjects', 'student_id')
    op.add_column('class_group_students', sa.Column('enrollment_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_class_group_students_student_id'), table_name='class_group_students')
    op.create_index(op.f('ix_class_group_students_enrollment_id'), 'class_group_students', ['enrollment_id'], unique=False)
    op.create_unique_constraint('uq_cg_enrollment', 'class_group_students', ['class_group_id', 'enrollment_id'])
    op.drop_constraint('class_group_students_student_id_fkey', 'class_group_students', type_='foreignkey')
    op.create_foreign_key(None, 'class_group_students', 'enrollments', ['enrollment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('class_group_students', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE class_group_students CASCADE")
    op.execute("TRUNCATE TABLE class_group_student_subjects CASCADE")
    op.add_column('class_group_students', sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'class_group_students', type_='foreignkey')
    op.create_foreign_key('class_group_students_student_id_fkey', 'class_group_students', 'users', ['student_id'], ['id'])
    op.drop_constraint('uq_cg_enrollment', 'class_group_students', type_='unique')
    op.drop_index(op.f('ix_class_group_students_enrollment_id'), table_name='class_group_students')
    op.create_index(op.f('ix_class_group_students_student_id'), 'class_group_students', ['student_id'], unique=False)
    op.drop_column('class_group_students', 'enrollment_id')
    op.add_column('class_group_student_subjects', sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'class_group_student_subjects', type_='foreignkey')
    op.create_foreign_key('class_group_student_subjects_student_id_fkey', 'class_group_student_subjects', 'users', ['student_id'], ['id'])
    op.drop_constraint('uq_cg_enrollment_subject', 'class_group_student_subjects', type_='unique')
    op.drop_index(op.f('ix_class_group_student_subjects_enrollment_id'), table_name='class_group_student_subjects')
    op.create_unique_constraint('uq_cg_student_subject', 'class_group_student_subjects', ['class_group_id', 'student_id', 'subject_id'])
    op.create_index(op.f('ix_class_group_student_subjects_student_id'), 'class_group_student_subjects', ['student_id'], unique=False)
    op.drop_column('class_group_student_subjects', 'enrollment_id')
    # ### end Alembic commands ###
