"""Add enrollment_code

Revision ID: 69bc40cce567
Revises: a8c092bdd6ac
Create Date: 2026-02-23 23:16:23.448662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69bc40cce567'
down_revision: Union[str, None] = 'a8c092bdd6ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('enrollment_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_enrollments_enrollment_code'), 'enrollments', ['enrollment_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollments_enrollment_code'), table_name='enrollments')
    op.drop_column('enrollments', 'enrollment_code')
    # ### end Alembic commands ###
