"""class group nullable semester

Revision ID: 0241e5f1a3a5
Revises: 0f4aee6ab87c
Create Date: 2026-02-21 18:21:00.047739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0241e5f1a3a5'
down_revision: Union[str, None] = '0f4aee6ab87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class_groups', 'semester',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class_groups', 'semester',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
