"""lesson plan class orders array

Revision ID: 57584c42507f
Revises: 0241e5f1a3a5
Create Date: 2026-02-21 18:37:23.789718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57584c42507f'
down_revision: Union[str, None] = '0241e5f1a3a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('class_order_item', sa.Integer(), nullable=True))
    op.add_column('lesson_plans', sa.Column('class_orders', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('lesson_plans', 'lesson_quantity')
    op.drop_column('lesson_plans', 'class_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_plans', sa.Column('class_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lesson_plans', sa.Column('lesson_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('lesson_plans', 'class_orders')
    op.drop_column('attendances', 'class_order_item')
    # ### end Alembic commands ###
